apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: soundcheck-external-demo
  description: SCE Demo Component
  annotations:
    sonarqube.org/project-key: wishihadakey
    pagerduty.com/integration-key: asdjakljdlksajdsjak
spec:
  type: website
  lifecycle: experimental
  owner: toast-infra
  system: soundcheck
