# Sample file - kubernetes/horizontalpodautoscaler.yaml
# Note: This is a sample file, please replace the content with the appropriate content for your entity
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: flask-react
  namespace: cs-alertify
  labels:
    app: flask-react
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-react
  maxReplicas: 10
  minReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
